# Setup
title:        Flyman's Blog
tagline:      Curious about different technologies
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Fei Zheng
  url:        https://github.com/flyman3046

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown